export const createAdminSlice = (set, get) => ({
    categories:[],
    products:[],
    orders:[],
    settings:{},
    currentProduct:null,
    coupons:[],
    passcodes:[],
    setCategories:(categories)=>{
        set((state)=>({
            ...state,
            categories:categories
        }))
    },
    setProducts:(products)=>{
        set((state)=>({
            ...state,
            products:products
        }))
    },
    setOrders:(orders)=>{
        set((state)=>({
            ...state,
            orders:orders
        }))
    },
    setCoupons:(coupons)=>{
        set((state)=>({
            ...state,
            coupons:coupons
        }))
    },
    setPasscodes:(passcodes)=>{
        set((state)=>({
            ...state,
            passcodes:passcodes
        }))
    },
    setCurrentProduct:(product)=>{
        set((state)=>({
            ...state,
            currentProduct:product
        }))
    },
    setSettings:(settings)=>{
        set((state)=>({
            ...state,
            settings:settings
        }))
    }
})
